import {CATALOG,CATEGORIES,ROOM_PRESETS,BUILDINGS,MATERIALS,getCatalog} from './catalog.js';
import {addItem,addRoom,template,concept,cost,snap,uid} from './sim.js';
import {load,save,exportFile} from './storage.js';
import {listAssets,putAssets,removeAsset,assetUrl,refreshUrls} from './asset-store.js';
const $=s=>document.querySelector(s), app=$('#app');
let REAL=[], S={project:load(),selected:null,level:0,query:'',cat:'All',zoom:.78,tool:'select',side:true,inspect:true,history:[],future:[],modal:null,pan:{x:0,y:0},realTab:'models'};
S.level=S.project.level??0;
const money=n=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n||0);
const clone=x=>JSON.parse(JSON.stringify(x));
const esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function boot(){REAL=await refreshUrls();render();}
function commit(p,sel=S.selected){S.history.push(clone(S.project));S.history=S.history.slice(-50);S.future=[];S.project={...p,updatedAt:new Date().toISOString()};S.selected=sel;save(S.project);render()}
function patchItem(p){if(!S.selected)return;commit({...S.project,items:S.project.items.map(i=>i.id===S.selected?{...i,...p}:i)})}
function selected(){return S.project.items.find(i=>i.id===S.selected)}
function add(id,x=100,y=100){const p=addItem(S.project,id,{level:S.level,x,y});commit(p,p.items.at(-1).id)}
function addReal(a){const item={id:uid(),catalogId:'real-'+a.id,name:a.name,category:a.kind==='model'?'Real 3D':'Real Image',icon:'3D',w:140,h:100,price:0,color:'#c9c1b6',level:S.level,x:180,y:180,rotation:0,scale:1,z:(S.project.items.length||1),variant:'Original',material:'Original',realAssetId:a.id,realKind:a.kind};commit({...S.project,items:[...S.project.items,item]},item.id)}
function del(){if(!S.selected)return;commit({...S.project,items:S.project.items.filter(i=>i.id!==S.selected)},null)}
function duplicate(){const i=selected();if(!i)return;const n={...i,id:uid(),x:i.x+30,y:i.y+30};commit({...S.project,items:[...S.project.items,n]},n.id)}
function undo(){if(!S.history.length)return;S.future.unshift(clone(S.project));S.project=S.history.pop();S.selected=null;render()}
function redo(){if(!S.future.length)return;S.history.push(clone(S.project));S.project=S.future.shift();S.selected=null;render()}
function roomAdd(preset){const r=ROOM_PRESETS[preset];commit(addRoom(S.project,...r,S.level),null)}
function level(l){S.level=l;S.project.level=l;S.selected=null;render()}
function fit(){S.zoom=.78;S.pan={x:0,y:0};render()}
function render(){app.innerHTML=`<header class="top"><div class="brand"><button class="mobile menu" data-a="side">☰</button><div class="logo">B</div><div><b>BuildSpace</b><small>German Housing Design Studio</small></div></div><div class="title"><b>${esc(S.project.name)}</b><span>${esc(S.project.address||'Neues Projekt')} · ${esc(S.project.client||'Privat')}</span></div><div class="topBtns"><button data-a="new">Neu</button><button data-a="save">Speichern</button><button data-a="export">Export</button><button class="primary" data-a="ai">✦ Konzept</button></div></header><div class="layout">${S.side?sidebar():''}<main class="work"><div class="bar"><div><button class="${S.tool==='select'?'on':''}" data-tool="select">↖ Auswahl</button><button class="${S.tool==='pan'?'on':''}" data-tool="pan">✥ Navigation</button><button data-a="undo">↶</button><button data-a="redo">↷</button></div><div class="view"><button data-a="minus">−</button><b>${Math.round(S.zoom*100)}%</b><button data-a="plus">＋</button><button data-a="fit">Fit</button></div><button data-a="inspect">☷ Eigenschaften</button></div><div class="canvas" id="canvas"><div class="scene" style="transform:translate(calc(-50% + ${S.pan.x}px),calc(-50% + ${S.pan.y}px)) scale(${S.zoom})">${scene()}</div></div><div class="levelsBottom">${[0,1,2,3].map(l=>`<button class="${S.level===l?'on':''}" data-level="${l}">${l===0?'EG':'OG '+l}</button>`).join('')}</div></main>${S.inspect?inspector():''}</div>${S.modal?modal():''}<nav class="mobileNav"><button data-a="side">☰<small>Assets</small></button><button data-a="ai">✦<small>Konzept</small></button><button data-a="fit">⌂<small>Ansicht</small></button><button data-a="inspect">☷<small>Edit</small></button></nav>`;bind()}
function realList(){const q=S.query.toLowerCase();return REAL.filter(a=>a.name.toLowerCase().includes(q)&&((S.realTab==='models'&&a.kind==='model')||(S.realTab==='images'&&a.kind==='image')))}
function sidebar(){const list=CATALOG.filter(c=>(S.cat==='All'||c.category===S.cat)&&c.name.toLowerCase().includes(S.query.toLowerCase()));const real=realList();return `<aside class="side"><div class="sideTop"><b>Bauteile & Einrichtung</b><button data-a="side">×</button></div><div class="quick"><button class="on" data-a="import">＋<span>Real Assets</span></button><button data-a="assetHelp">?</button><button data-a="clearSearch">⌕<span>Suche</span></button></div><div class="realBox"><div class="realTitle"><b>Meine echten Assets</b><span>${REAL.length}</span></div><div class="realTabs"><button class="${S.realTab==='models'?'on':''}" data-real="models">3D / GLB</button><button class="${S.realTab==='images'?'on':''}" data-real="images">Bilder</button></div>${real.length?real.map(a=>`<button class="asset realAsset" data-realadd="${a.id}"><div class="realThumb">${a.kind==='model'?'<span>3D</span>':`<img src="${assetUrl(a.id)}">`}</div><div><b>${esc(a.name)}</b><small>${a.kind==='model'?'GLB / GLTF':'PNG / JPG / WEBP'}</small></div><i>＋</i></button>`).join(''):'<div class="empty">Importiere Möbel als GLB oder transparente PNG/WebP-Dateien.</div>'}<button class="importWide" data-a="import">＋ Echte Möbel importieren</button></div><h4>Geschosse</h4><div class="levels">${[0,1,2,3].map(l=>`<button class="${S.level===l?'on':''}" data-level="${l}"><strong>${l===0?'EG':l}</strong>${l===0?'Erdgeschoss':'Obergeschoss '+l}</button>`).join('')}</div><h4>Raum anlegen</h4><div class="roomGrid">${ROOM_PRESETS.map((r,i)=>`<button data-room="${i}"><span>${r[0].slice(0,2)}</span>${r[0]}</button>`).join('')}</div><h4>Gebäude-Vorlagen</h4><div class="buildings">${BUILDINGS.map((b,i)=>`<button data-build="${i}"><b>${b[0]}</b><small>${b[1]}</small></button>`).join('')}</div><div class="catHead"><h4>Design Assets</h4><span>${list.length}</span></div><div class="search"><span>⌕</span><input id="q" value="${esc(S.query)}" placeholder="Sofa, Küche, Fenster…"></div><div class="chips">${['All',...CATEGORIES].map(c=>`<button class="${S.cat===c?'on':''}" data-cat="${c}">${c}</button>`).join('')}</div><div class="assets">${list.map(c=>`<button class="asset" data-add="${c.id}"><div class="thumb" style="--c:${c.color}"><span>${c.icon}</span></div><div><b>${c.name}</b><small>${c.category} · ${money(c.price)}</small></div><i>＋</i></button>`).join('')}</div></aside>`}
function visual(i){if(i.realAssetId){const u=assetUrl(i.realAssetId);if(i.realKind==='model'&&u)return `<model-viewer class="realModel" src="${u}" camera-controls="false" interaction-prompt="none" disable-zoom shadow-intensity="0.6" exposure="1" camera-orbit="35deg 65deg 2.5m" field-of-view="28deg" style="width:100%;height:100%;background:transparent"></model-viewer>`;if(u)return `<img class="realImage" src="${u}" alt="">`}return `<div class="assetShape" style="--c:${i.color}"><strong>${getCatalog(i.catalogId)?.icon||'ASSET'}</strong><span>${esc(i.name)}</span></div>`}
function scene(){const rooms=S.project.rooms.filter(r=>r.level===S.level),items=S.project.items.filter(i=>i.level===S.level).sort((a,b)=>a.z-b.z);return `<div class="floor"><div class="grid"></div>${rooms.map(r=>`<div class="room" style="left:${r.x}px;top:${r.y}px;width:${r.w}px;height:${r.h}px;background:${r.color}"><div class="wall topw"></div><div class="wall leftw"></div><div class="wall rightw"></div><div class="roomName"><b>${r.name}</b><small>${r.style} · ${Math.round(r.w*r.h/10000)} m²</small></div></div>`).join('')}${items.map(i=>`<div class="obj ${S.selected===i.id?'sel':''}" data-id="${i.id}" style="left:${i.x}px;top:${i.y}px;width:${i.w}px;height:${i.h}px;z-index:${i.z};transform:rotate(${i.rotation}deg) scale(${i.scale})">${visual(i)}${S.selected===i.id?`<button class="handle rotate" data-rot="${i.id}">↻</button><button class="handle delete" data-del="${i.id}">×</button>`:''}</div>`).join('')}</div>`}
function inspector(){const i=selected();return `<aside class="inspect"><div class="insTop"><div><b>${i?esc(i.name):'Eigenschaften'}</b><small>${i?(i.realAssetId?'Echtes Asset':'Design Asset'):'Projekt / Auswahl'}</small></div><button data-a="inspect">×</button></div>${i?`<div class="tabs"><b>Asset</b><span>Position</span><span>Stil</span></div><label>Asset Name<input data-p="name" value="${esc(i.name)}"></label><div class="two"><label>X<input type="number" data-p="x" value="${i.x}"></label><label>Y<input type="number" data-p="y" value="${i.y}"></label></div><div class="two"><label>Breite<input type="number" data-p="w" value="${i.w}"></label><label>Tiefe<input type="number" data-p="h" value="${i.h}"></label></div><div class="two"><label>Drehung<input type="number" data-p="rotation" value="${i.rotation}"></label><label>Skalierung<input type="number" step=".05" data-p="scale" value="${i.scale}"></label></div>${!i.realAssetId?`<label>Designvariante<select data-p="variant">${(getCatalog(i.catalogId)?.variants||[]).map(v=>`<option ${v===i.variant?'selected':''}>${v}</option>`).join('')}</select></label><label>Material<select data-p="material">${MATERIALS.map(v=>`<option ${v===i.material?'selected':''}>${v}</option>`).join('')}</select></label>`:''}<div class="actions"><button data-a="duplicate">Duplizieren</button><button data-a="rot">90°</button><button class="danger" data-a="delete">Löschen</button></div>${i.realAssetId?`<button class="removeReal" data-a="removeReal">Asset aus Bibliothek entfernen</button>`:''}`:`<div class="project"><label>Projektname<input data-proj="name" value="${esc(S.project.name)}"></label><label>Bauherr / Kunde<input data-proj="client" value="${esc(S.project.client||'')}"></label><label>Adresse<input data-proj="address" value="${esc(S.project.address||'')}"></label><label>Budget (€)<input type="number" data-proj="budget" value="${S.project.budget||0}"></label><label>Notizen<textarea data-proj="notes">${esc(S.project.notes||'')}</textarea></label><div class="stats"><b>${S.project.items.filter(x=>x.level===S.level).length}<small>Assets</small></b><b>${money(cost(S.project))}<small>Wert EG/OG</small></b></div></div>`}</aside>`}
function modal(){if(S.modal==='help')return `<div class="modalBack"><div class="modal"><button class="close" data-a="close">×</button><h2>Realistische Assets</h2><p>Für Sims-artige Möbel brauchst du echte <b>GLB/GLTF 3D-Modelle</b> oder transparente <b>PNG/WebP</b>-Renderings. Importiere sie hier direkt vom Handy. Die Bibliothek wird im Browser gespeichert.</p><ol><li>Furniture Kit von Kenney herunterladen.</li><li>ZIP entpacken.</li><li>Mehrere .glb Dateien auswählen.</li><li>Sie erscheinen unter „Meine echten Assets“.</li></ol><p>Für die beste mobile Performance zuerst etwa 20–40 Modelle importieren, nicht 140 gleichzeitig auf der Szene.</p><button class="primary wide" data-a="close">Verstanden</button></div></div>`;if(S.modal==='ai')return `<div class="modalBack"><div class="modal"><button class="close" data-a="close">×</button><h2>✦ Raumkonzept</h2><p>Beschreibe den gewünschten Raum. BuildSpace setzt daraus eine komplette Einrichtung zusammen.</p><textarea id="prompt" placeholder="z.B. modernes deutsches Wohnzimmer mit Eiche, Sofa, TV-Wand, Pflanzen und warmem Licht"></textarea><div class="suggest">${['Modernes deutsches Wohnzimmer','Bauhaus Küche mit Insel','Japandi Schlafzimmer','Berliner Loft Arbeitszimmer'].map(x=>`<button data-suggest="${x}">${x}</button>`).join('')}</div><button class="primary wide" data-a="generate">Konzept anwenden</button></div></div>`;return ''}
function bind(){document.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>act(b.dataset.a));document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>{S.tool=b.dataset.tool;render()});document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>level(+b.dataset.level));document.querySelectorAll('[data-room]').forEach(b=>b.onclick=()=>roomAdd(+b.dataset.room));document.querySelectorAll('[data-build]').forEach(b=>b.onclick=()=>commit(template(S.project,BUILDINGS[+b.dataset.build][0]),null));document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{S.cat=b.dataset.cat;render()});document.querySelectorAll('[data-real]').forEach(b=>b.onclick=()=>{S.realTab=b.dataset.real;render()});document.querySelectorAll('[data-realadd]').forEach(b=>b.onclick=()=>addReal(REAL.find(x=>x.id===b.dataset.realadd)));document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>add(b.dataset.add));const q=$('#q');if(q)q.oninput=e=>{S.query=e.target.value;render()};document.querySelectorAll('[data-id]').forEach(el=>{el.onpointerdown=e=>drag(e,el.dataset.id);el.onclick=e=>{e.stopPropagation();S.selected=el.dataset.id;S.inspect=true;render()}});document.querySelectorAll('[data-del]').forEach(b=>b.onclick=e=>{e.stopPropagation();S.selected=b.dataset.del;del()});document.querySelectorAll('[data-rot]').forEach(b=>b.onclick=e=>{e.stopPropagation();S.selected=b.dataset.rot;patchItem({rotation:(selected().rotation+15)%360})});document.querySelectorAll('[data-p]').forEach(el=>el.oninput=e=>{let v=e.target.value;const t=el.dataset.p;if(['x','y','w','h','rotation','scale'].includes(t))v=Number(v);patchItem({[t]:v})});document.querySelectorAll('[data-proj]').forEach(el=>el.oninput=e=>{S.project={...S.project,[el.dataset.proj]:el.type==='number'?Number(e.target.value):e.target.value};save(S.project)});document.querySelectorAll('[data-suggest]').forEach(b=>b.onclick=()=>$('#prompt').value=b.dataset.suggest);const c=$('#canvas');if(c){c.ondragover=e=>e.preventDefault();c.ondrop=e=>{const id=e.dataTransfer?.getData('asset');if(id)add(id,100,100)}}}
function drag(e,id){if(S.tool!=='select')return;e.preventDefault();S.selected=id;S.inspect=true;const i=selected(),sx=e.clientX,sy=e.clientY,ix=i.x,iy=i.y;let moved=false;const mv=v=>{moved=true;i.x=snap(ix+(v.clientX-sx)/S.zoom);i.y=snap(iy+(v.clientY-sy)/S.zoom);const el=document.querySelector(`[data-id="${id}"]`);if(el){el.style.left=i.x+'px';el.style.top=i.y+'px'}};const up=()=>{document.removeEventListener('pointermove',mv);if(moved){S.history.push(clone({...S.project,items:S.project.items.map(x=>x.id===id?{...x,x:i.x,y:i.y}:x)}));S.project.updatedAt=new Date().toISOString();save(S.project)}render()};document.addEventListener('pointermove',mv);document.addEventListener('pointerup',up,{once:true})}
async function importReal(){
      const input=document.createElement('input');

        input.type='file';
          input.multiple=true;
            input.accept='*/*';

              input.style.position='fixed';
                input.style.left='-9999px';
                  document.body.appendChild(input);

                    input.onchange=async()=>{
                        try{
                              const files=[...input.files];

                                    if(!files.length){
                                            input.remove();
                                                    return;
                                                          }

                                                                const allowed=files.filter(f =>
                                                                        /\.(glb|gltf|png|jpg|jpeg|webp)$/i.test(f.name)
                                                                              );

                                                                                    if(!allowed.length){
                                                                                            alert('Keine unterstützte Datei gefunden. Bitte GLB, GLTF, PNG, JPG oder WEBP auswählen.');
                                                                                                    input.remove();
                                                                                                            return;
                                                                                                                  }

                                                                                                                        REAL=await putAssets(allowed);

                                                                                                                              S.query='';
                                                                                                                                    S.realTab=allowed.some(f =>
                                                                                                                                            /\.(glb|gltf)$/i.test(f.name)
                                                                                                                                                  ) ? 'models' : 'images';

                                                                                                                                                        render();

                                                                                                                                                            }catch(err){
                                                                                                                                                                  console.error('Asset import error:',err);
                                                                                                                                                                        alert('Import fehlgeschlagen: '+err.message);
                                                                                                                                                                            }finally{
                                                                                                                                                                                  input.remove();
                                                                                                                                                                                      }
                                                                                                                                                                                        };

                                                                                                                                                                                          document.body.appendChild(input);
                                                                                                                                                                                            input.click();
}
async function act(a){if(a==='side')S.side=!S.side;else if(a==='inspect')S.inspect=!S.inspect;else if(a==='undo')undo();else if(a==='redo')redo();else if(a==='new'){S.project=load();S.project.name='Neues Wohnprojekt';S.selected=null}else if(a==='save'){save(S.project);S.project.updatedAt=new Date().toISOString()}else if(a==='export')exportFile(S.project);else if(a==='ai')S.modal='ai';else if(a==='help'||a==='assetHelp')S.modal='help';else if(a==='import')await importReal();else if(a==='clearSearch'){S.query='';S.cat='All';render()}else if(a==='close')S.modal=null;else if(a==='generate'){S.project=concept(S.project,$('#prompt').value);S.modal=null;S.selected=null}else if(a==='duplicate')duplicate();else if(a==='delete')del();else if(a==='removeReal'){const i=selected();if(i?.realAssetId){await removeAsset(i.realAssetId);REAL=await listAssets();S.selected=null;render()}}else if(a==='rot')patchItem({rotation:(selected().rotation+90)%360});else if(a==='plus')S.zoom=Math.min(1.5,S.zoom+.08);else if(a==='minus')S.zoom=Math.max(.4,S.zoom-.08);else if(a==='fit')fit();render()}
window.onkeydown=e=>{if((e.ctrlKey||e.metaKey)&&e.key==='z')undo();if((e.ctrlKey||e.metaKey)&&e.key==='y')redo();if(e.key==='Delete')del()};setInterval(()=>save(S.project),5000);boot();
